# Generated by Django 3.0.8 on 2020-07-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoForHolidayApp', '0002_remove_placeinfo_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeinfo',
            name='arrivalTime',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeinfo',
            name='departureTime',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeinfo',
            name='experience',
            field=models.TextField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
