# Generated by Django 3.0.8 on 2020-07-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoForHolidayApp', '0003_auto_20200717_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinfo',
            name='arrivalTime',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='placeinfo',
            name='departureTime',
            field=models.CharField(max_length=200),
        ),
    ]
